import {
  mobile,
  backend,
  creator,
  web,
  javascript,
  typescript,
  html,
  css,
  reactjs,
  redux,
  tailwind,
  nodejs,
  mongodb,
  git,
  figma,
  docker,
  threejs,
  meta,
  starbucks,
  tesla,
  shopify,
  csus,
  western,
  stoica,
  imggen,
  stoicasite,
  convexhullex,
} from "../assets";

export const navLinks = [
  {
    id: "about",
    title: "About",
  },
  {
    id: "work",
    title: "Work",
  },
  {
    id: "contact",
    title: "Contact",
  },
];

const services = [
  {
    title: "Machine Learning Developer",
    icon: backend,
  },
  {
    title: "React JS Developer",
    icon: mobile,
  },
  {
    title: "Competitive Programmer",
    icon: creator,
  },
  {
    title: "Algorithm Designer",
    icon: web,
  },
];

const technologies = [
  {
    name: "HTML 5",
    icon: html,
  },
  {
    name: "CSS 3",
    icon: css,
  },
  {
    name: "JavaScript",
    icon: javascript,
  },
  /*{
    name: "TypeScript",
    icon: typescript,
  },*/
  {
    name: "React JS",
    icon: reactjs,
  },
  /*{
    name: "Redux Toolkit",
    icon: redux,
  },*/
  {
    name: "Tailwind CSS",
    icon: tailwind,
  },
  {
    name: "Node JS",
    icon: nodejs,
  },
  {
    name: "MongoDB",
    icon: mongodb,
  },
  {
    name: "Three JS",
    icon: threejs,
  },
  {
    name: "git",
    icon: git,
  },
  {
    name: "figma",
    icon: figma,
  },
  /*{
    name: "docker",
    icon: docker,
  },*/
];

const experiences = [
  {
    title: "Algorithm Designer",
    company_name: "UWO Directed Reading Program",
    icon: western,
    iconBg: "#383E56",
    date: "Sep 2022 - Dec 2022",
    points: [
      "Utilize PyCharm IDE, Matplotlib visualization tool and Vim text editor to execute a Convex Hull Visualization.",
      "Implemented version control using Git via GitHub.",
    ],
  },
  {
    title: "React JS Developer",
    company_name: "Western Computer Science Undergraduate Society",
    icon: csus,
    iconBg: "#383E56",
    date: "Nov 2022 - May 2023",
    points: [
      "Development of an all-encompassing student hub web application for the University of Western Ontario.",
      "Intended for reading and writing reviews on buildings, study spots, campus eateries, etc., to help over 40,000+ students.",
    ],
  },
  {
    title: "Software Developer Intern",
    company_name: "Stoica",
    icon: stoica,
    iconBg: "#E6DEDD",
    date: "Sept 2022 - Present",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Developing and maintaining a cross-platform, Android and iOS, application using Flutter and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
    ],
  },
  /*{
    title: "Full stack Developer",
    company_name: "Meta",
    icon: meta,
    iconBg: "#E6DEDD",
    date: "Jan 2023 - Present",
    points: [
      "Developing and maintaining web applications using React.js and other related technologies.",
      "Collaborating with cross-functional teams including designers, product managers, and other developers to create high-quality products.",
      "Implementing responsive design and ensuring cross-browser compatibility.",
      "Participating in code reviews and providing constructive feedback to other developers.",
    ],
  },*/
];

/*const testimonials = [
  {
    testimonial:
      "I thought it was impossible to make a website as beautiful as our product, but Rick proved me wrong.",
    name: "Sara Lee",
    designation: "CFO",
    company: "Acme Co",
    image: "https://randomuser.me/api/portraits/women/4.jpg",
  },
  {
    testimonial:
      "I've never met a web developer who truly cares about their clients' success like Rick does.",
    name: "Chris Brown",
    designation: "COO",
    company: "DEF Corp",
    image: "https://randomuser.me/api/portraits/men/5.jpg",
  },
  {
    testimonial:
      "After Rick optimized our website, our traffic increased by 50%. We can't thank them enough!",
    name: "Lisa Wang",
    designation: "CTO",
    company: "456 Enterprises",
    image: "https://randomuser.me/api/portraits/women/6.jpg",
  },
];*/

const projects = [
  {
    name: "AI Image Generator",
    description:
      "Web-based platform that allows users to browse and create a collection of imaginative and visually stunning images generated by DALL-E AI.",
    tags: [
      {
        name: "MERN_Stack",
        color: "blue-text-gradient",
      },
      {
        name: "OpenAI_API",
        color: "green-text-gradient",
      },
      {
        name: "tailwindcss",
        color: "pink-text-gradient",
      },
    ],
    image: imggen,
    source_code_link: "https://github.com/murtaza147/dall-e_clone",
    live_demo_link: "https://murts-dalle-clone.netlify.app/",
  },
  {
    name: "Stoica Web Application",
    description:
      "Web application that enables users to download the Stoica mobile app, learn Stoica's mission statement and stay up to date with the latest updates.",
    tags: [
      {
        name: "react",
        color: "blue-text-gradient",
      },
      {
        name: "tailwindcss",
        color: "green-text-gradient",
      },
      {
        name: "figma",
        color: "pink-text-gradient",
      },
    ],
    image: stoicasite,
    source_code_link: "https://github.com/murtaza147/WorldDomination",
  },
  {
    name: "Convex Hull Visualization",
    description:
      "An algorithmic visualization tool that allows users to visualize the convex hull of a set of points.",
    tags: [
      {
        name: "python",
        color: "blue-text-gradient",
      },
      {
        name: "matplotlib",
        color: "green-text-gradient",
      },
      {
        name: "numpy",
        color: "pink-text-gradient",
      },
    ],
    image: convexhullex,
    source_code_link: "https://github.com/murtaza147/DRP-Fall-Winter-2022",
  },
];

export { services, technologies, experiences, /*testimonials,*/ projects };
